name: build and test project

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.0'

      - name: run-format-check
        run: gofmt -l app/*.go

      - name: run-linter
        uses: golangci/golangci-lint-action@v2
        
      - name: install-dependencies
        run: go get ./...
          
      - name: build
        run: go build -v ./...

      - name: test
        run: go test -v ./...
